spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

