name: Verify Staged Artifacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 5.0.0-M1, 5.1.0-RC1, 5.2.0 etc.'
        required: true
        type: string

jobs:
  verify-staged-with-samples:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Samples Repo
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-integration
          show-progress: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.52.2
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Configure JFrog Cli
        run: jf gradlec --repo-resolve libs-staging-local

      - name: Verify Spring Integration Kafka against staged release
        run: |
          sed -i "1,/springKafkaVersion.*/s/springKafkaVersion.*/springKafkaVersion='${{ inputs.releaseVersion }}'/" build.gradle
          jf gradle :spring-integration-kafka:check

      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/target/surefire-reports/**/*.*'
          retention-days: 1